## filename: environment.yml

## Environment File Definition

name: polymath # polymath with tensorflow-gpu environment, hopefully
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python=3.9.5
  - pip
  - tensorflow-gpu
  - cudnn
  - cudatoolkit
  - pip:
    - crepe==0.0.13
    - librosa==0.9.2
    - numpy>=1.20
    - pyrubberband==0.3.0
    # - pyrubberband-cli
    - sf_segmenter==0.0.2
    - soundfile==0.11.0
    - yt_dlp==2023.02.17
    - demucs==4.0.0
    - basic-pitch==0.2.0
    - matplotlib
    - tensorflow==2.9
